import { defineConfig } from 'vocs/config'

export default defineConfig({
  title: 'Splits Guidebook',
  description: 'Guides, workflows, and FAQs for using Splits.',
  topNav: [
    { text: 'splits.org', link: 'https://splits.org' },
    { text: 'GitHub', link: 'https://github.com/0xSplits' },
  ],
  sidebar: [
    {
      text: 'Welcome',
      link: '/',
    },
    {
      text: 'Getting started',
      items: [
        { text: 'The basics - start here', link: '/getting-started/the-basics' },
        { text: 'Creating a team', link: '/getting-started/creating-a-team' },
        { text: 'Adding signers', link: '/getting-started/adding-signers' },
        { text: 'Adding teammates as signers', link: '/getting-started/adding-teammates-as-signers' },
        { text: 'Connecting to other apps', link: '/getting-started/connecting-to-other-apps' },
        { text: 'Earning interest', link: '/getting-started/earning-interest' },
        { text: 'Swapping', link: '/getting-started/swapping' },
        { text: 'On/offramping', link: '/getting-started/on-offramping' },
        { text: 'Showing/hiding tokens (spam)', link: '/getting-started/showing-hiding-tokens' },
        { text: 'Accounting', link: '/getting-started/accounting' },
        { text: 'Schedules', link: '/getting-started/schedules' },
        { text: 'Network support', link: '/getting-started/network-support' },
        { text: 'Asset support', link: '/getting-started/asset-support' },
        { text: 'Verifying signers', link: '/getting-started/verifying-signers' },
        { text: 'Custom transactions', link: '/getting-started/custom-transactions' },
        { text: 'Invoicing', link: '/getting-started/invoicing' },
        { text: 'Automations', link: '/getting-started/automations' },
        { text: 'Programmatic Access via Splits CLI', link: '/getting-started/splits-cli' },
        { text: 'Batch transactions', link: '/getting-started/batch-transactions' },
        { text: 'Splits for teams of one', link: '/getting-started/splits-for-teams-of-one' },
      ],
    },
    {
      text: 'Workflows',
      collapsed: false,
      items: [
        { text: 'Using Splits to escrow an OTC deal', link: '/workflows/escrow-an-otc-deal' },
        { text: 'Use an ENS name with Splits', link: '/workflows/use-an-ens-name' },
        { text: 'Incorporating and banking in the US', link: '/workflows/incorporating-and-banking-in-the-us' },
        { text: 'Receiving investor funding onchain', link: '/workflows/receiving-investor-funding-onchain' },
        { text: 'Viewing and claiming vesting tokens', link: '/workflows/viewing-and-claiming-vesting-tokens' },
        { text: 'Viewing and claiming liquidity position (LP) rewards', link: '/workflows/viewing-and-claiming-lp-rewards' },
        { text: 'Using Splits with splitter contracts', link: '/workflows/using-splits-with-splitter-contracts' },
        { text: 'Batch swapping long-tail tokens', link: '/workflows/batch-swapping-long-tail-tokens' },
        { text: 'Auto-withhold for taxes in USDC', link: '/workflows/auto-withhold-for-taxes' },
        { text: 'Automating token transfers', link: '/workflows/automating-token-transfers' },
        { text: 'Automating custom transactions', link: '/workflows/automating-custom-transactions' },
        { text: 'Recovering your accounts', link: '/workflows/recovering-your-accounts' },
        { text: 'Transforming appcoins into working capital', link: '/workflows/transforming-appcoins-into-working-capital' },
        { text: 'Repaying loans from Clanker fees', link: '/workflows/repaying-loans-from-clanker-fees' },
        { text: 'Raising capital onchain', link: '/workflows/raising-capital-onchain' },
        { text: 'Recover assets from unsupported networks', link: '/workflows/recover-assets-from-unsupported-networks' },
        { text: 'Using corporate cards with Splits', link: '/workflows/using-corporate-cards' },
        { text: 'Manage a Farcaster account', link: '/workflows/manage-a-farcaster-account' },
        { text: 'Suggested security settings based on team size', link: '/workflows/suggested-security-settings' },
      ],
    },
    {
      text: 'FAQs',
      collapsed: false,
      items: [
        { text: 'Can I refer my friends?', link: '/faqs/refer-friends' },
        { text: 'What jurisdictions are supported for on/offramps?', link: '/faqs/onramp-jurisdictions' },
        { text: 'What transaction fees are sponsored?', link: '/faqs/sponsored-fees' },
        { text: 'How can I verify my Splits account on Farcaster?', link: '/faqs/verify-on-farcaster' },
        { text: 'Can I import an existing account?', link: '/faqs/import-existing-account' },
        { text: 'Why isn’t my passkey opening?', link: '/faqs/passkey-not-opening' },
        { text: 'Can I change Recovery signers?', link: '/faqs/change-recovery-signers' },
      ],
    },
    {
      text: 'Our outlook & usage patterns',
      collapsed: false,
      items: [
        { text: 'Our stack', link: '/outlook/our-stack' },
        { text: 'How we think about contract security', link: '/outlook/contract-security' },
        { text: 'How we secure our assets', link: '/outlook/how-we-secure-our-assets' },
        { text: 'How we make money', link: '/outlook/how-we-make-money' },
        { text: 'Why recovery matters', link: '/outlook/why-recovery-matters' },
        { text: 'How we got here', link: '/outlook/how-we-got-here' },
        { text: 'Who has control', link: '/outlook/who-has-control' },
      ],
    },
    {
      text: 'About us',
      collapsed: false,
      items: [
        { text: 'Mission & vision', link: '/about/mission-and-vision' },
        { text: 'Values & culture', link: '/about/values-and-culture' },
        { text: 'Writing culture', link: '/about/writing-culture' },
      ],
    },
  ],
})
